name: 'Build AUR Package'
branding:
  icon: user-check
  color: gray-dark
inputs:
  repo-name:
    description: 'AUR repository name to build'
    required: true
  preinstallPkgs:
    description: 'packages need install before build, separated by space'
    required: false
    default: ""
runs:
  using: 'docker'
  image: "ghcr.io/chenxiex/arch-build/build-aur-action-image:latest"
  env:
    INPUTS_PREINSTALLPKGS: ${{ inputs.preinstallPkgs }}
  args:
    - ${{ inputs.repo-name }}
