[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"

[setpl-git]
source = "git"
git = "https://github.com/horshack-dpreview/setPL.git"
use_commit = true

[v2rayn-bin]
source = "aur"

[howdy-git]
source = "git"
git = "https://github.com/boltgolt/howdy.git"
use_commit = true

[steam-devices-git]
source = "git"
git = "https://github.com/ValveSoftware/steam-devices.git"
use_commit = true

[gnome-shell-extension-gjs-osk-git]
source = "git"
git = "https://github.com/Vishram1123/gjs-osk.git"
use_commit = true

[nvtray-git]
source = "git"
git = "https://github.com/chenxiex/nvtray.git"
use_commit = true